### ISSUE TITLE
How to generate a session history key from an AssistantV2 session?

### ISSUE THREAD

**Issue by andrucz** [watson-developer-cloud/assistant-web-chat-service-desk-starter#44]
I've implemented a bridge between SMS and Watson assistants and would like to generate a session history key so that I can use the agent app.

Could you guys disclose how those keys are generated based on a session?

https://github.com/watson-developer-cloud/assistant-web-chat-service-desk-starter/blob/3e2629417b592a5c3ea64522e3e078f0e917b216/src/flex/agentApp/src/WatsonAssistantAgentAppPlugin.tsx#L33

**Comment by ethanwinters** [comment]
Currently, this is a private API only used by the web chat. I have forwarded this on to the PM team as a request to open.
